### ISSUE TITLE
php static function call from class

### ISSUE THREAD

**Issue by ivitaly** [pug-php/pug#116]
Seems there some problems around static classes and maybe namespaces

// php file
```php
class Util {
    static function Function() {
          return "sample";
    }
}
```

// pug file
```pug
section#my
      =Util::Function()
```

**Comment by kylekatarnls** [comment]
I tried the following static call on http://pug-demo.herokuapp.com/:

```pug
section
  =DateTime::createFromFormat('j-M-Y', '15-Feb-2009')->format('Y-m-d')
```

And I get:
```html
<section>
  2009-02-15 
</section>
```

This is the expected behaviour.

I also tested creating a class and static method locaaly and it works well too.

To get a faster help, please follow the pattern given in the [guidelines](https://github.com/pug-php/pug/blob/master/CONTRIBUTING.md#issue-contributions): 

[Issue pattern](https://github.com/pug-php/pug/issues/new?body=Hello%2C%0A%0AI%20encountered%20an%20issue%20with%20the%20following%20code%3A%0A%60%60%60pug%0Ap%20Some%20example%0A%60%60%60%0A%0AI%20expected%20to%20get%3A%0A%60%60%60html%0A%3Cp%3ESome%20example%3C%2Fp%3E%0A%60%60%60%0A%0ABut%20I%20actually%20get%3A%0A%60%60%60html%0A%3Cp%3ESomething%20else%3C%2Fp%3E%0A%60%60%60%0A%0AThanks!)

It must at least include your code, the result you get and the result you expect.

Thanks,
