### ISSUE TITLE
Symbols {} escaped to %7B%7D

### ISSUE THREAD

**Issue by Riant** [pug-php/pug#120]
Hello,

I encountered an issue with the following code:
```pug
a(title=$userinfo['user_name'] .'{{hello}}' href=URL::route('ucenter/del_item') .'?id={{id}}') Delete
```

I expected to get:
```html
<a title="xxx{{hello}}" href="//192.168.xx.xx:4000/ucenter/del-item?id={{id}}">Delete</a>
```

But I actually get:
```html
<a title="xxx{{hello}}" href="//192.168.xx.xx:4000/ucenter/del-item?id=%7B%7Bid%7D%7D">Delete</a>
```
I am using [Laravel-pug](https://github.com/BKWLD/laravel-pug) for now, and I do not know if it's a pug-php issue.

Thanks!

**Comment by kylekatarnls** [comment]
Hi,

To know if an error occurs on pug-php or from your framework extension, you can test your code in http://pug-demo.herokuapp.com/

I tried with:
```pug
a(title=$userinfo['user_name'] .'{{hello}}' href=strtolower('ucenter/del_item') .'?id={{id}}') Delete
```
I just replaced `URL::route` since it's Laraval facade. And with the data:
```php
array(
  'userinfo' => array(
    'user_name' => 'Bob'
  ),
)
```
I get the expected result:
```html
<a title="Bob{{hello}}" href="ucenter/del_item?id={{id}}">Delete</a>
```

Are you up to date with your dependencies? Is this code in a mixin? Have some `&attributes()`stuff?

So it seems there is a urlencode feature in laravel-pug or laravel, it could be here:
https://github.com/BKWLD/laravel-pug/blob/master/src/PugBladeCompiler.php#L47

But I'm not sure.

If you cannot reproduce it with pug-php only, you should open an issue on laravel-pug and I will try to help them to fix it.

**Comment by Riant** [comment]
Thanks, it looks like Laravel did attributes urlencode.

**Comment by rulatir** [comment]
What is the current working URL for that pug sandbox?
