### ISSUE TITLE
add nodejs-php-fallback as suggestion

### ISSUE THREAD

**Issue by s4msung** [pug-php/pug#132]
I don't have have any use for this dependency at all

**Comment by kylekatarnls** [comment]
nodejs-php-fallback is required for the pugjs option (allow to call native pug-cli node package).

In fact, neither js-phpize nor nodejs-php-fallback is needed with the default options. But that's why autoload exist, if you use default options, these packages are never loaded. But if you need the options, there are yet available with no more installation. And the nodejs-php-fallback hook allow to download the pug-cli package, so the option could not work properly with just using suggest.

Is there a reason to remove it?

**Comment by kylekatarnls** [comment]
Be aware many engines and frameworks embed classes, dependencies, and many things you may not use. For example, if you use jQuery, you probably don't use every function in every project. It's a choice we have to make between, give an easy to use all-in-one project and targeted light project that imply the user must know and install many packages.

With the new version, you will be able to use the engine alone (https://github.com/phug-php/phug) or even just use the compiler/parser/lexer. Phug will come with no JS or JS-syntax support at all. Then an install tool will ask some questions about preferences and suggest some installations for plugins.

So I close this issue for the moment. If nodejs-php-fallback break some functionality please reopen this issue and let me know.

**Comment by kylekatarnls** [comment]
Planned and specified: https://github.com/pug-php/pug/issues/171

**Comment by kylekatarnls** [comment]
With 3.0.1, pug-cli will be asked to the user before install.
