### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by neooblaster** [pug-php/pug#133]
Hi Kyle,

I'm new on pug-php.
I'm interested by PUG (formerly Jade) because writing HTML tags is so annoying and huge files can become hard to maintain. On my side, i have a homemade Template Engine, so i made an interface to exploit both engine in easy way.

I would like to know if there is a user guide / manual where i can find all existing methods (Public function).
If not i would like to contribute by making/participate on it.

Also, i would like to tell you there is some missing parenthesis on some code samples :

```php
$pug = new Pug(array(
    'prettyprint' => true,
    'extension' => '.pug',
    'cache' => 'pathto/writable/cachefolder/'
);
```

Indeed, There is closing parenthesis for Array(), but not for Pug() instanciation.

Best Regards.
Neoblaster.

French Version :
J'ai vu que tu étais localisé en France. 
Je tente une version FR : Il manque la parenthèse de fermeture pour l'appel de la classe Pug

```php
$pug = new Pug(array('prettyprint' => true, 'extension' => '.pug','cache' => 'pathto/writable/cachefolder/');
```

**Comment by kylekatarnls** [comment]
Hi neooblaster,

There is only the PHPDoc (documentation in comments) and you can create the documentation from it with https://www.phpdoc.org/, it give: http://jade.selfbuild.fr/classes/Jade.Jade.html but is version is not at all up to date.

I'm aware there are a lot of features nobody can use just because of the lack of documentation.

But before taking time with the documentation, you must know we are working on a complete refactorization of Pug: https://github.com/phug-php/phug

Both current and next versions need documentation but I would focus on the new project first.

I invited you on our slack chat to discuss further about this if you're still interested.

Thanks,

**Comment by neooblaster** [comment]
Hi Kyle,

I understand, on my side, Documentation is done after the release of Engine.
Writing documentations take so many time !
That why i want to help on that subject. That will help you and also users which use this engine !

In the afternoon, i will get a look on https://www.phpdoc.org/ to know more about.

Where can i find informations about slack chat ? 
It's a GitHub Messaging App ?

UPDATE
I just saw the invitation to slack service... So it's OK.
END UPDATE

Thanks for your reply.
Neooblaster.

**Comment by kylekatarnls** [comment]
At least, the phpdoc is now up to date: http://jade.selfbuild.fr/namespaces/Jade.html

Examples for main method could be added in comments to make this documentation more useful.

**Comment by neooblaster** [comment]
I close Issue #133.
Issue reported is now fixed.
About documentation, that will done over the time.

**Comment by kylekatarnls** [comment]
@neooblaster and other people that would be interested in contributing to the documentation:

This is the documentation project: https://github.com/phug-php/website

And the temporarlay URL to preview it: https://phug.selfbuild.fr
