### ISSUE TITLE
Interpolation does not support null coalescing operator

### ISSUE THREAD

**Issue by char101** [pug-php/pug#235]
Hello,

With the variables set as `['a' => 10]`

I encountered an issue with the following code:
```pug
p #{ a ?? 'a' }
```

I expected to get:
```html
<p>10</p>
```

But I actually get:
```
Use of undefined constant a - assumed 'a' (this will throw an Error in a future version of PHP) on line 2, offset 4
```

Thanks!

**Comment by kylekatarnls** [comment]
Hello, `??` does not exist in JS.

As your expression is in JS-style, you should use:
```pug
p #{ a || 'a' }
```

Or to match exactly the behavior of `??`:
```pug
p #{ a === null ? 'a' : 10 }
```

Else in PHP-style:
```pug
p #{ $a ?? 'a' }
```

Thanks.

**Comment by char101** [comment]
Hi, thanks for the prompt answer. Since `#{ a }` works I was assuming it was php style expression without `$` prefix for variables (ala Twig) but apparently it was the library doing _magic tricks_ 😁 .

**Comment by kylekatarnls** [comment]
What exactly happens is `a ?? 'a'` failed to be parsed as a JS expression so it's evaluated as is by PHP but `a` constant does not exist, that's why other expression above work.

Note: I discovered the meaning of "ala" here https://www.yourdictionary.com/ala
For the side story, I'm French and "ala" does not exist in French, we would say "à la Twig" as a familiar short-hand for "à la manière de Twig" the definition given by this dictionary is right for "prepared in a certain way" ("à la" may match this part of the definition), but as for "or for a particular" and the "chicken ala king" example, that definitely does not come from the French language. ^^

**Comment by char101** [comment]
Thanks for the explanation. I wasn't familiar yet with the ecosystem for the library. So `pug-php` by default renders expression using js style with `js-phpize`.

As a side note, I am Indonesian, and in this language, _ala_ means exactly like _a la_ in French, which is _in the style of_, which is why I confuse the two 😁 .
