### ISSUE TITLE
parse php function  error

### ISSUE THREAD

**Issue by rokite** [pug-php/pug#33]
```
protected function handleArgumentValue($arg)
{
   //fix parse php function error, add **strlen($arg) == 1**
    if (preg_match('/^([\'"]).*?\1/', $arg) && strlen($arg) == 1) {
        return $this->handleString(trim($arg));
    }

    try {
        return $this->handleCode($arg);
    } catch (\Exception $e) {
        // if a bug occur, try to remove comments
        try {
            return $this->handleCode(preg_replace('#/\*(.*)\*/#', '', $arg));
        } catch (\Exception $e) {
            throw new \Exception('Pug.php did not understand ' . $arg, 10, $e);
        }
    }
}
```

**Comment by kylekatarnls** [comment]
Please provide a template example to get the error to occur.

Thanks.

**Comment by kylekatarnls** [comment]
Hi, it seems your code is invalid because our regex capture strings between quotes like `"xx"` in **$arg** so if the regex match, it will never have a 1-char length. It seems this hack just disable `handleString`. You really should'nt do that.

If you get an error, please provide the error and the template you use, we will inspect them.

Thanks.
